{{- $sa := default dict .Values.serviceAccount }}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "boutique-services.name" .) $sa.name }}
  labels:
    {{- include "boutique-services.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automount | default false }}
{{- end }}
