# Values for the authentication service.
nameOverride: auth

image:
  repository: sanketwadekar3/auth-service
  tag: b7d0a24
  pullPolicy: IfNotPresent

containerPort: 3002

env:
  - name: NODE_ENV
    value: development
  - name: PORT
    value: "3002"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: boutique-secrets
        key: AUTH_DB_URL
