# Values for the React frontend.
nameOverride: frontend

image:
  repository: sanketwadekar3/boutique-frontend
  tag: 4ae78e3
  pullPolicy: IfNotPresent

containerPort: 3000

env:
  - name: REACT_APP_API_URL
    value: "http://gateway:3001/api"
