# Values for the order history service.
nameOverride: orders

image:
  repository: sanketwadekar3/orders-service
  tag: 4ae78e3
  pullPolicy: IfNotPresent

containerPort: 3005

env:
  - name: NODE_ENV
    value: development
  - name: PORT
    value: "3005"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: boutique-secrets
        key: ORDERS_DB_URL
  - name: PRODUCTS_SERVICE_URL
    value: "http://product-service:3003"
