apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique

resources:
  - namespace.yml
  - k8s/database/statefulset.yml
  - k8s/database/service.yml
  - k8s/database/restore-job.yml
  # - k8s/grafana-dashboard.yml

configMapGenerator:
  - name: boutique-db-dump
    files:
      - k8s/database/boutique_full.sql

generatorOptions:
  disableNameSuffixHash: true
